name: Cent Kilos 4 Cent Cols
favicon: null
layout_spectrum: 0.019884430803358555
typography_spectrum: 0.519960509147495
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8571519437246025
  lightness: 0.5073620106559247
  saturation: 0.8417117146309465
  rhythmicContrast: 0.08654318354092538
purpose: []
